<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows10.0.17763.0</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>360</AssemblyName>
    <RootNamespace>Trirex360.Desktop</RootNamespace>
    <Version>1.0.17</Version>
    <AssemblyVersion>1.0.17.0</AssemblyVersion>
    <FileVersion>1.0.17.0</FileVersion>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>Resources\360.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.3179.45" />
  </ItemGroup>

  <ItemGroup>
    <None Update="appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Resources\360.ico" />
  </ItemGroup>

</Project>
